

-- Mostrar bases de datos 
-- SHOW es para mostrar elementos
show databases;

-- CREA UNA BASE DE DATOS DE PRUEBAS 
CREATE DATABASE DUMMY_DB;

-- DESPUES DE EJECUTAR USE, TODOS LOS COMANDOS EJECUTADOS AFECTARAN SOLAMENTE DUMMY_DB EN ESTE CASO
USE DUMMY_DB;

-- DEFINIENDO UNA TABLA EN MYSQL
-- CREATE TABLE - SIGNIFICA QUE VA A CREAR UNA 
-- EMPLEADOS ES EL NOMBRE Y DENTRO DE LOS PARENTESIS VAN LOS CAMPOS/COLUMNAS DE LA TABLA Y LOS 
-- VALORES ESPERADOS EN ESTAS.
CREATE TABLE EMPLEADOS(ID int,  NOMBRE VARCHAR(200), APELLIDO VARCHAR(200));

-- SELECCIONAR/VER
-- * TODOS LOS CAMPOS/REGISTROS 
-- FROM QUE PERTENECEN A 
-- NOMBRE DE LA TABLA 'EMPLEADO'
SELECT * FROM EMPLEADOS;


-- INSERTAR DENTRO DE EMPLEADOS (NOMBRE DE LOS CAMPOS A INSERTAR) VALORES A INSERTAR( VALORES SEGUN DEFINICION)
INSERT INTO EMPLEADOS(ID, NOMBRE, APELLIDO) VALUES( 111000, 'JARED', 'PINEDA');


-- CREANDO DUMMYTABLE PARA LUEGO HACER LO QUE QUERAMOS SOBRE ESTA
CREATE TABLE DUMMY_TABLE( DUMMY_ID int, DUMMY_VAL varchar(100));

-- INSERTANDO UN VALOR EN DUMMYTABLE
INSERT INTO DUMMY_TABLE(DUMMY_ID) VALUE(1000);

-- SELECCIONA SOLO UN CAMPO/COL DE DUMMYTABLE
SELECT DUMMY_ID FROM DUMMY_TABLE;

-- ELIMINAR TODOS LOS REGISTROS
DELETE FROM DUMMY_TABLE WHERE DUMMY_ID IS NOT NULL;
-- EN ESTA SESSION HACER LOS CAMBIOS
COMMIT;

-- VERIFICANDO Q SE ELIMINO TODO DE DUMMYTABLE
SELECT * FROM DUMMY_TABLE;


-- ELIMINAR DUMMYTABLE COMO TABLA
DROP TABLE DUMMY_TABLE;

-- MOSTRAR LAS TABLAS PARA VER Q SI SE ELIMINO DUMMYTABLE
SHOW TABLES;















